# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/openjdk:8-jdk-node-browsers

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run:
         name: Install the CPIC Kit
         command: npm install

    - run:
        name: Test CPIC Kit
        command: npm start && mkdir test-results && npm test


    - run:
        name: Create CPIC Kit zip ready for deployment
        command: npm run package


    - run:
        name: Deploy VuePress GitHub Pages
        command: |
              .circleci/vuepress_deploy,sh


    - store_artifacts:
          path: dist

    - store_test_results:
        path: test-results
