# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/openjdk:11-jdk-node-browsers

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run:
        name:
        command: java -version && node -v

    - run:
         name: Install dependencies
         command: npm install

    # - run:
    #     name: Test CPIC Demo
    #     command: npm start && mkdir test-results && npm test
    #
    # - run:
    #     name: Create CPIC Demo zip ready for deployment
    #     command: npm run package

    - run:
        name: Deploy VuePress GitHub Pages
        command: |
             git config --global user.email "$GIT_USER_EMAIL"
             git config --global user.name "$GIT_USER_NAME"

             chmod 777 .circleci/vuepress_deploy.sh && .circleci/vuepress_deploy.sh

             git tag $RELEASE
             git push origin $RELEASE

    - store_artifacts:
          path: docs/.vuepress/dist/app

    - store_test_results:
        path: test-results

workflows:
  version: 2
  main:
    jobs:
    - build:
        context: kgrid-demos
        filters:
          branches:
            only: master
